### ISSUE TITLE
Syslog Tuning per SSH not working

### ISSUE THREAD

**Issue by hansi941** [dcecchino/glog#12]
Hello,

I wanted to follow your steps in "Tune your esxi syslog configuration via ssh" but unfortunately my esxi is missing some of your metioned files.
You described some sed commands for the following files:

- /etc/vmware/vpxa/vpxa.cfg
- /etc/vmware/hostd/config.xml
- /etc/vmware/rhttpproxy/config.xml 
- /etc/opt/vmware/fdm/fdm.cfg  
- /etc/vmware/hostd/probe-config.xml

But my esxi has only the following files:
- /etc/vmware/rhttpproxy/config.xml
- /etc/opt/vmware/fdm/fdm.cfg

My ESXi Version is:  
- VMware ESXi, 7.0.3, 18825058 

Do I miss something or how can I generate those files.
Or is there an alternative way to set those log levels globally?

Thanks in advanced
Best regards

Hansi

**Comment by dcecchino** [comment]
Hello,
You are running latest vmware 7 , I've not tested versions above 7.0.3, but see this article and the one below. If you find the correct syntax to edit the verbose to error only for the files above, please post it in this thread and I will update the documentation 

https://kb.vmware.com/s/article/87438

In previous releases (before ESXi 7.0U3) you may be instructed by other KB article(s) to change some settings of ESXi service "vpxa" by directly editing its configuration file (/etc/vmware/vpxa/vpxa.cfg) manually and restarting the "vpxa" service.

The settings in the database are accessible by a tool: /bin/configstorecli 


Same goes for hostd and most likely the other services,.

https://kb.vmware.com/s/article/82227
