### ISSUE TITLE
 "ERROR [GrokPatternRegistry] Unable to load grok pattern Alert Level"

### ISSUE THREAD

**Issue by nick199310** [dcecchino/glog#13]
fter switching to a newer version of graylog, a source does not send logs. It only sends the old one. After I removed the logs from the server, I noticed that the error "ERROR [GrokPatternRegistry] Unable to load grok pattern Alert Level" appeared, can someone help me to correct the [error](url)

[grok pattern.txt](https://github.com/dcecchino/glog/files/9422203/grok.pattern.txt)

**Comment by dcecchino** [comment]
You have an issue with your ossec security grok expression, but this is the wrong forum for this, please go to the ossec graylog page.


GrokPatternRegistry] Unable to load grok pattern Alert Level: %{BASE10NUM:OSSEC_Alert_Level};
