### ISSUE TITLE
Unknown field: Query contains unknown field: failure_type

### ISSUE THREAD

**Issue by goofy79** [dcecchino/glog#15]
In the Dashboard "VMware Security Events" we can not see any entry in the "Login Failure Past Day username/source ip" widget ?
If we press the "play" Button in the Widget - i get the Error "Unknown field: Query contains unknown field: failure_type" 

If we search for "Authentication failure" we find this entry 

{
  "gl2_accounted_message_size": 257,
  "level": 5,
  "gl2_remote_ip": "xxx.xxx.xxx.xxx",
  "gl2_remote_port": 61862,
  "streams": [
    "000000000000000000000001"
  ],
  "gl2_message_id": "01GSCN6SJ0DPXCRWMNVA9PFJJZ",
  "source": "esxi-34",
  "message": "esxi-34 DCUI[2100792]: pam_unix(dcui:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root",
  "gl2_source_input": "63eb861cfca7a04742945d27",
  "facility_num": 10,
  "gl2_source_node": "0b63ce27-e340-4f38-bcd7-ddc91dc5b514",
  "_id": "5d494120-add3-11ed-921a-005056973ded",
  "facility": "security/authorization",
  "timestamp": "2023-02-16T08:24:43.000Z"
}

**Comment by dcecchino** [comment]
If ip_address or ipv4 field isn’t being extracted there may be an issue with dns lookups.On Feb 16, 2023, at 4:00 AM, goofy79 ***@***.***> wrote:﻿
In the Dashboard "VMware Security Events" we can not see any entry in the "Login Failure Past Day username/source ip" widget ?
If we press the "play" Button in the Widget - i get the Error "Unknown field: Query contains unknown field: failure_type"
If we search for "Authentication failure" we find this entry
{
"gl2_accounted_message_size": 257,
"level": 5,
"gl2_remote_ip": "xxx.xxx.xxx.xxx",
"gl2_remote_port": 61862,
"streams": [
"000000000000000000000001"
],
"gl2_message_id": "01GSCN6SJ0DPXCRWMNVA9PFJJZ",
"source": "esxi-34",
"message": "esxi-34 DCUI[2100792]: pam_unix(dcui:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root",
"gl2_source_input": "63eb861cfca7a04742945d27",
"facility_num": 10,
"gl2_source_node": "0b63ce27-e340-4f38-bcd7-ddc91dc5b514",
"_id": "5d494120-add3-11ed-921a-005056973ded",
"facility": "security/authorization",
"timestamp": "2023-02-16T08:24:43.000Z"
}

**Comment by goofy79** [comment]
OK, but it isn't a lookup problem right ? 
The field "failure_type" isn't there ?

**Comment by dcecchino** [comment]
What version of esxi are you running? I hope the below is a hostname number 😀"source": "esxi-34","message": "esxi-34 DCUI[2100792]: On Feb 16, 2023, at 4:00 AM, goofy79 ***@***.***> wrote:﻿
In the Dashboard "VMware Security Events" we can not see any entry in the "Login Failure Past Day username/source ip" widget ?
If we press the "play" Button in the Widget - i get the Error "Unknown field: Query contains unknown field: failure_type"
If we search for "Authentication failure" we find this entry
{
"gl2_accounted_message_size": 257,
"level": 5,
"gl2_remote_ip": "xxx.xxx.xxx.xxx",
"gl2_remote_port": 61862,
"streams": [
"000000000000000000000001"
],
"gl2_message_id": "01GSCN6SJ0DPXCRWMNVA9PFJJZ",
"source": "esxi-34",
"message": "esxi-34 DCUI[2100792]: pam_unix(dcui:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root",
"gl2_source_input": "63eb861cfca7a04742945d27",
"facility_num": 10,
"gl2_source_node": "0b63ce27-e340-4f38-bcd7-ddc91dc5b514",
"_id": "5d494120-add3-11ed-921a-005056973ded",
"facility": "security/authorization",
"timestamp": "2023-02-16T08:24:43.000Z"
}

**Comment by goofy79** [comment]
We have Version 7.0u1 and yes - "esxi-34" is the Hostname :)

**Comment by dcecchino** [comment]
So this dashboard panel is for ssh connections not DCUI (main login screen) to vmware.  I see what's going on for example,


Should you ssh to the host, this dashboard should populate if you give the wrong password. You see below, you get this error "Authentication failure" with ssh 

hostname sshd[8629772]: error: PAM: Authentication failure for root from 10.10.10.3

However, if you simply login to the via the console and put in an incorrect password, then you won't see any errors and the fields won't be updated because there is no extractor (regex) or (grok) for this type of DCUI log entry only ssh. I can write in for future improvements, but not at the moment. You may create extractions for this using grok and extract out the fields username, source to injest this type of log entry. 

hostname DCUI: pam_unix(dcui:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost= user=root

**Comment by dcecchino** [comment]
Hello,

I've updated the vmware_vcenter_extractors , apply this to your vmware esxi input not the vcenter input. The last two entries are for the dcui login. 

Finally update your "Login Failure Past Day username/source ip" panel

failure_type:"Authentication failure" OR failure_type:Failed OR failure_type:"User not known to the underlying authentication module" OR failure_type:"authentication failure"

If its still not displaying the dcui logs update that panel to remove the ip_address field.

**Comment by goofy79** [comment]
ok, if i use a unknown username on webinterface like "superadministartor" no extractor match ....
i have the following messages 

from the ESXi
`esxi-17 Hostd: error hostd[2099859] [Originator@6876 sub=Default opID=esxui-79c8-7aaa] [module:pam_lsass]pam_do_authenticate: error [login:Superadministrator][error code:2]`

`esxi-17 Hostd: warning hostd[2099859] [Originator@6876 sub=Default opID=esxui-79c8-7aaa] Rejected password for user Superadministrator from 192.168.0.10`

`esxi-17 Hostd: info hostd[2099859] [Originator@6876 sub=Vimsvc.ha-eventmgr opID=esxui-79c8-7aaa] Event 4126063 : Cannot login Superadministrator@192.168.0.10`

`esxi-17 Hostd: --> "Superadministrator"`

from VCenter
`Event [18500469] [1-1] [2023-02-17T10:22:59.156124Z] [vim.event.BadUsernameSessionEvent] [error] [Superadministrator] [anywhere] [18500469] [Cannot login Superadministrator@192.168.0.10]`

**Comment by dcecchino** [comment]
Is the dcui login resolved? The web interface is a different extraction that will need to be built.On Feb 17, 2023, at 5:36 AM, goofy79 ***@***.***> wrote:﻿
ok, if i use a unknown username on webinterface like "superadministartor" no extractor match ....
i have the following messages
from the ESXi
esxi-17 Hostd: error hostd[2099859] ***@***.*** sub=Default opID=esxui-79c8-7aaa] [module:pam_lsass]pam_do_authenticate: error [login:Superadministrator][error code:2]
esxi-17 Hostd: warning hostd[2099859] ***@***.*** sub=Default opID=esxui-79c8-7aaa] Rejected password for user Superadministrator from 192.168.0.10
esxi-17 Hostd: info hostd[2099859] ***@***.*** sub=Vimsvc.ha-eventmgr opID=esxui-79c8-7aaa] Event 4126063 : Cannot login ***@***.***
esxi-17 Hostd: --> "Superadministrator"
from VCenter
Event [18500469] [1-1] [2023-02-17T10:22:59.156124Z] [vim.event.BadUsernameSessionEvent] [error] [Superadministrator] [anywhere] [18500469] [Cannot login ***@***.***

**Comment by dcecchino** [comment]
Okay  download and apply the latest vmware_vcenter_extractors to your esxi, then update the dashboard panel with this search and save it. This is the last custom modification I do ;-) 

failure_type:"Authentication failure" OR failure_type:Failed OR failure_type:"User not known to the underlying authentication module" OR "Cannot login"  OR failure_type:"authentication failure" OR failure_type:"pam_do_authenticate"
