### ISSUE TITLE
Document contains at least one immense term in field="vmware_release"

### ISSUE THREAD

**Issue by marcolefo** [dcecchino/glog#19]
Hi

Like in https://github.com/dcecchino/glog/issues/17 and https://github.com/dcecchino/glog/issues/18
but for vmware_release

Graylog 5.2.1
Opensearch 2.11.0
vcenter 8.0.2
ESXi 7.0.3

Complete error message
`OpenSearchException[OpenSearch exception [type=illegal_argument_exception, reason=Document contains at least one immense term in field="vmware_release" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped. Please correct the analyzer to not produce such terms. The prefix of the first immense term is: '[82, 101, 108, 101, 97, 115, 101, 92, 110, 47, 73, 110, 118, 101, 110, 116, 111, 114, 121, 83, 116, 97, 116, 115, 47, 80, 114, 111, 112, 101]...', original message: bytes can be at most 32766 in length; got 64267]]; nested: OpenSearchException[OpenSearch exception [type=max_bytes_length_exceeded_exception, reason=bytes can be at most 32766 in length; got 64267]];`

Extractor configuration
Extractor type: Regular expression
Source field: message
Regular expression: option=(.*)

**Comment by dcecchino** [comment]
Vcenter 8 not supported at this time
