### ISSUE TITLE
VMware Last resort extractor marks non VMWare log messages

### ISSUE THREAD

**Issue by qaxi** [dcecchino/glog#4]
**Describe the bug**
VMware Last resort extractor marks non VMWare log messages.

**To Reproduce**
1. Install extractors on SyslogUDP input
2. Find message not comming from VMWare
3. You can see "VMware_EventID"

**Expected behavior**
In log messages comming from NON VMWare you should not find "VMware_EventID" ...

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/3974128/92871139-e529f480-f404-11ea-935d-150d36ea56a0.png)

**Comment by qaxi** [comment]
Possible solutions:

1. Remove "Last resort" extractors.
2. Specify and point out that your set of extractors need solo input just for VMWare logs (is it possible to add it to _content_pack.json_ ? and possibly with extractors attached)

**Comment by dcecchino** [comment]
QAXI- Thank you for your find. It's always a good practice to have a dedicated bucket for your incoming syslog messages such as vmware port / log file. Or a dedicated port for your input buckets. I will add some notes to the documentation about solo input.
