### ISSUE TITLE
Import JSON File

### ISSUE THREAD

**Issue by augandi** [dcecchino/glog#5]
Hi,

I hope you can help me with the JSON Code for the extractor. I got a Syntax error when I am trying to import. This is the issue: SyntaxError: Unexpected token ] in JSON at position 149994

I have no idea where the problem is :(

**Comment by cgendrew** [comment]
have same issue, please assist

**Comment by cgendrew** [comment]
actually just fixed it using json formatter and it found issue and automatically corrected it. Was able to upload extractors correctly afterwards. Give the following txt file a shot. @augandi 

[vmware_vcenter_extractors.txt](https://github.com/dcecchino/glog/files/5637053/vmware_vcenter_extractors.txt)

**Comment by markusg80** [comment]
@cgendrew Thx i will try this

**Comment by chench00** [comment]
Pasted in a Json Lint and found line 3330 has `},` (the 4th line from the bottom). 
Remove the comma so it's just `}`

**Comment by augandi** [comment]
Okay, I was able to import the JSON File now. I tried out the web JSON LINT and with this I found the syntax error. Thank you very much!

I have a second question but I think I will post it as a new question.
