### ISSUE TITLE
Duplicates in vmware_vcenter_extractors

### ISSUE THREAD

**Issue by engren** [dcecchino/glog#6]
I've been converting the vmware_vcenter_extractors file in this repo from extractors to pipelines and noticed that there are tons of duplicates that does the same thing.

The file is in desperate need of a cleanup to avoid hogging systems that want to stick with input extractors..

**Comment by dcecchino** [comment]
Thanks for your inputs, it definitely needs to be cleaned up I do agree.  At the moment that is on my todo list. A lot of the grok searches seem repetitive, however each extraction has been uniquely identified by individual syslog entries. If you could provide an example of where you see duplicate issues, I can correct the ones that you see. Please feel to post here.

**Comment by dcecchino** [comment]
Will continue to review the extractors and update/revise as necessary, please feel to re-open a new issue with the extractors in question. Thanks!

**Comment by petroid** [comment]
```
$ grep grok_pattern vmware_vcenter_extractors.txt | wc -l
236
$ grep grok_pattern vmware_vcenter_extractors.txt | sort | uniq --count | wc -l
130
```
As of now almost half of extractors (130 of 236) are duplicates. That means exactly same grok pattern.

**Comment by dcecchino** [comment]
I haven’t had time to review them, but my plan is to migrate away from grok to regex.

>

**Comment by petroid** [comment]
My colleague cleaned extractors list a bit, so I took a liberty to share #7 . That gave our graylog setup a performance boost from ~160msg/s to ~580msg/s.

**Comment by dcecchino** [comment]
Regex will be even faster, but glad things are working for you. Please like my graylog vmware extractor on the marketplace if you glog is helping you out.
